# Generated by Django 5.0.3 on 2024-03-21 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('popular_courses', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('gross_tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_of_living', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('earliest_intake', models.CharField(max_length=100)),
                ('program_duration', models.IntegerField(choices=[(2, '2 Years'), (3, '3 Years'), (4, '4 Years')], default=2)),
                ('program_type', models.CharField(choices=[('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree')], max_length=50)),
                ('application_deadline', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.university')),
            ],
        ),
    ]
