# Generated by Django 5.0.3 on 2024-03-17 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('gross_tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_of_living', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('earliest_intake', models.DateField()),
                ('program_duration', models.CharField(max_length=50)),
                ('program_type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('application_deadline', models.DateField()),
            ],
        ),
    ]
