# Generated by Django 5.0.3 on 2024-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='range_tution_fee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
