# Generated by Django 5.0.3 on 2024-03-17 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_earliest_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='application_deadline',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost_of_living',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='gross_tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_duration',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree")], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='university_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
