# Generated by Django 5.0.3 on 2024-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_range_tution_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='range_tution_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='application_deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree')], max_length=50, null=True),
        ),
    ]
