# Generated by Django 5.0.3 on 2024-03-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_application_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_duration',
            field=models.IntegerField(choices=[(2, '2 Years'), (3, '3 Years'), (4, '4 Years')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree")], default='Unknown', max_length=50),
        ),
    ]
