# Generated by Django 5.0.3 on 2024-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_program_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='application_deadline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='earliest_intake',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_type',
            field=models.CharField(choices=[('Bachelors Degree', 'Bachelors Degree'), ('Masters Degree', 'Masters Degree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='university_name',
            field=models.CharField(max_length=100),
        ),
    ]
