# Generated by Django 5.0.3 on 2024-03-26 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost_of_living',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='gross_tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_duration',
            field=models.IntegerField(choices=[(2, '2 Years'), (3, '3 Years'), (4, '4 Years')], default=2, null=True),
        ),
    ]
