# Generated by Django 5.0.3 on 2024-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_cost_of_living_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='UnitedStates', max_length=100),
        ),
    ]
